name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  loop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scripts:
          - build
          - lint
          - check

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      # - name: Cache node_modules
      #   id: node_modules_cache_id
      #   uses: actions/cache@v4
      #   with:
      #     path: node_modules
      #     key: npm-deps-${{ hashFiles('package-lock.json') }}
      #     restore-keys: npm-deps-

      - name: Install Dependencies
        # if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: "npm install"

      - run: "npm run ${{ matrix.scripts}}"
